<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CommsManager.Application/CommsManager.Application.csproj" />
    <ProjectReference Include="../CommsManager.Infrastructure/CommsManager.Infrastructure.csproj" />
  </ItemGroup>

</Project>
